openapi: 3.0.0
info:
  title: Todo-List
  description: Todo-list API
  version: 0.1.9

servers:
  - url: https://todolist-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /todo:
    post:
      tags:
        - Todo list
      requestBody:
        description: create todo list
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                todo:
                  type: string
      responses:
        "200":
          description: todo list created
    get:
      tags:
        - Todo list
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                done:
                  type: boolean
    put:
      tags:
        - Todo list
      requestBody:
        description: update feedback
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                todo:
                  type: string
                done:
                  type: boolean
      responses:
        "200":
          description: todo updated
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Todo list
      responses:
        "200":
          description: feedback deleted
