openapi: 3.0.0
info:
  title: Todo-List
  description: Todo-list API
  version: 0.1.9

servers:
  - url: https://designed-api.onrender.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /todo:
    post:
      tags:
        - Todo List
      requestBody:
        description: create todo list
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                todo:
                  type: string
      responses:
        "200":
          description: todo list created
    get:
      tags:
        - Todo lists
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
